package ru.warland.core;

import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.arguments.*;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.server.command.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.item.Items;
import net.minecraft.text.Text;
import net.minecraft.util.math.BlockPos;
import ru.warland.api.WarLandApi.MenuEntry;
import ru.warland.data.Store;
import ru.warland.ui.Menus;
import java.util.*;
import java.time.*;
import static net.minecraft.server.command.CommandManager.*;

public final class CoreCommands {
 private CoreCommands(){}
 private static ServerPlayerEntity player(CommandContext<ServerCommandSource> c)throws CommandSyntaxException{return c.getSource().getPlayerOrThrow();}
 private static String str(CommandContext<ServerCommandSource> c,String name){return StringArgumentType.getString(c,name);}
 public static void register(CoreRuntime r){CommandRegistrationCallback.EVENT.register((d,registries,env)->{
  d.register(literal("warland").executes(c->{main(r,player(c));return 1;})
   .then(literal("tutorial").executes(c->{tutorial(r,player(c),0);return 1;}))
   .then(literal("status").executes(c->{c.getSource().sendFeedback(()->Text.literal("WarLand alpha | ready="+r.ready()+" | modules="+String.join(", ",r.modules)+" | /warland — меню"),false);return 1;})));
  d.register(literal("balance").executes(c->{var p=player(c);if(r.gate(p))r.later(p,r.balance(p.getUuid()).thenApply(v->"Баланс: "+v+" кредитов"));return 1;}));
  d.register(literal("nation").executes(c->{nation(r,player(c));return 1;})
   .then(literal("create").then(argument("name",StringArgumentType.word()).executes(c->{var p=player(c);String name=str(c,"name");if(!r.gate(p))return 0;r.confirm(p,"Основать государство",name+" • "+r.config.nationCost+" кредитов",()->{BlockPos at=p.getBlockPos();var w=p.getEntityWorld();if(!r.canBuild(p,w,at)||!w.getRegistryKey().getValue().toString().equals("minecraft:overworld")){r.reply(p,"Основать государство можно только в свободной дикой местности Верхнего мира.");return;}r.later(p,r.nations.create(p.getUuid(),name,w.getRegistryKey().getValue().toString(),at.getX(),at.getY(),at.getZ()));});return 1;})))
   .then(literal("invite").then(argument("player",StringArgumentType.word()).executes(c->{ServerPlayerEntity p=player(c),target=r.server().getPlayerManager().getPlayer(str(c,"player"));if(target==null){r.reply(p,"Игрок должен быть онлайн.");return 0;}if(r.gate(p)){r.later(p,r.nations.invite(p.getUuid(),target.getUuid()).thenApply(v->{r.server().execute(()->{var n=r.nations.nation(p.getUuid());if(n!=null)r.reply(target,"Приглашение в «"+n.name()+"»: /nation join "+n.name());});return v;}));}return 1;})))
   .then(literal("join").then(argument("name",StringArgumentType.word()).executes(c->{var p=player(c);if(r.gate(p))r.later(p,r.nations.join(p.getUuid(),str(c,"name")));return 1;})))
   .then(literal("leave").executes(c->{var p=player(c);if(r.gate(p))r.confirm(p,"Покинуть государство","Права на территории будут потеряны",()->r.later(p,r.nations.leave(p.getUuid())));return 1;}))
   .then(literal("deposit").then(argument("amount",LongArgumentType.longArg(1,1000000000)).executes(c->{var p=player(c);long amount=LongArgumentType.getLong(c,"amount");if(r.gate(p))r.confirm(p,"Пополнить казну",amount+" кредитов",()->r.later(p,r.nations.transfer(p.getUuid(),amount,false)));return 1;})))
   .then(literal("withdraw").then(argument("amount",LongArgumentType.longArg(1,1000000000)).executes(c->{var p=player(c);long amount=LongArgumentType.getLong(c,"amount");if(r.gate(p))r.confirm(p,"Вывести из казны",amount+" кредитов",()->r.later(p,r.nations.transfer(p.getUuid(),amount,true)));return 1;})))
   .then(literal("tax").then(argument("percent",IntegerArgumentType.integer(0,15)).executes(c->{var p=player(c);int amount=IntegerArgumentType.getInteger(c,"percent");if(r.gate(p))r.confirm(p,"Изменить налог",amount+"% • задержка 24 часа",()->r.later(p,r.nations.tax(p.getUuid(),amount)));return 1;})))
   .then(literal("rank").then(argument("player",StringArgumentType.word()).then(argument("rank",StringArgumentType.word()).executes(c->{ServerPlayerEntity p=player(c),t=r.server().getPlayerManager().getPlayer(str(c,"player"));if(t==null){r.reply(p,"Игрок должен быть онлайн");return 0;}if(r.gate(p))r.later(p,r.nations.rank(p.getUuid(),t.getUuid(),str(c,"rank")));return 1;}))))
   .then(literal("rankcreate").then(argument("name",StringArgumentType.word()).then(argument("permissions",StringArgumentType.word()).executes(c->{var p=player(c);if(r.gate(p))r.later(p,r.nations.defineRank(p.getUuid(),str(c,"name"),str(c,"permissions")));return 1;}))))
   .then(literal("pact").then(argument("nation",StringArgumentType.word()).executes(c->{var p=player(c);String target=str(c,"nation");if(r.gate(p))r.confirm(p,"Пакт о ненападении",target+" • 7 дней после подтверждения",()->r.later(p,r.nations.pact(p.getUuid(),target)));return 1;}))));
  d.register(literal("claim").executes(c->{var p=player(c);if(!r.gate(p))return 0;r.confirm(p,"Занять чанк",r.config.claimCost+" кредитов из казны",()->{var w=p.getEntityWorld();var at=p.getBlockPos();if(r.safe(w,at)){r.reply(p,"Спавн нельзя приватить");return;}r.later(p,r.nations.claim(p.getUuid(),w.getRegistryKey().getValue().toString(),at.getX()>>4,at.getZ()>>4));});return 1;})
   .then(literal("info").executes(c->{var p=player(c);var at=p.getBlockPos();String n=r.nations.claim(p.getEntityWorld().getRegistryKey().getValue().toString(),at.getX()>>4,at.getZ()>>4);r.reply(p,"Чанк "+(at.getX()>>4)+", "+(at.getZ()>>4)+": "+(r.safe(p.getEntityWorld(),at)?"безопасный хаб":n==null?"дикая местность":r.nations.snapshot().nations().get(n).name()));return 1;})));
  d.register(literal("war").executes(c->{war(r,player(c));return 1;})
   .then(literal("declare").then(argument("nation",StringArgumentType.word()).executes(c->{var p=player(c);String target=str(c,"nation");if(r.gate(p))r.confirm(p,"Объявить войну",target+" • "+r.config.warCost+" из казны • 12 ч подготовки",()->r.later(p,r.wars.declare(p.getUuid(),target)));return 1;})))
   .then(literal("peace").then(argument("nation",StringArgumentType.word()).executes(c->{var p=player(c);String target=str(c,"nation");if(r.gate(p))r.confirm(p,"Предложить или принять мир",target+" • подтверждение обеими сторонами за 10 минут • текущие территории сохраняются",()->r.later(p,r.wars.peace(p.getUuid(),target)));return 1;})))
   .then(literal("surrender").then(argument("nation",StringArgumentType.word()).executes(c->{var p=player(c);String target=str(c,"nation");if(r.gate(p))r.confirm(p,"Подтвердить капитуляцию",target+" • ваша сторона проиграет войну • дополнительного изъятия ресурсов нет",()->r.later(p,r.wars.surrender(p.getUuid(),target)));return 1;}))));
  d.register(literal("spawn").executes(c->{var p=player(c);if(r.gate(p))r.teleport(p,"spawn");return 1;}));
  d.register(literal("warp").executes(c->{var p=player(c);if(r.gate(p)){List<MenuEntry> entries=new ArrayList<>();for(String name:r.warps.keySet())entries.add(new MenuEntry(Menus.icon(Items.COMPASS,name,"Перемещение с задержкой"),()->r.teleport(p,name)));r.menu(p,"Транспорт",entries);}return 1;})
   .then(argument("name",StringArgumentType.word()).executes(c->{var p=player(c);if(r.gate(p))r.teleport(p,str(c,"name"));return 1;})));
  d.register(literal("home").executes(c->{var p=player(c);var n=r.nations.nation(p.getUuid());if(n==null){r.reply(p,"Вы не состоите в государстве");return 0;}var w=r.server().getWorld(net.minecraft.registry.RegistryKey.of(net.minecraft.registry.RegistryKeys.WORLD,net.minecraft.util.Identifier.of(n.dimension())));if(w!=null){r.registerWarp("capital-"+n.id(),w,new BlockPos(n.x(),n.y(),n.z()));if(r.gate(p))r.teleport(p,"capital-"+n.id());}return 1;}));
  d.register(literal("report").then(argument("player",StringArgumentType.word()).then(argument("reason",StringArgumentType.greedyString()).executes(c->{var p=player(c);String target=str(c,"player"),body=str(c,"reason");if(!r.gate(p))return 0;if(target.length()>32||body.length()>500){r.reply(p,"Описание не более 500 символов");return 0;}String loc=p.getEntityWorld().getRegistryKey().getValue()+" "+p.getBlockPos().toShortString();r.later(p,r.store.tx(db->{if(Store.scalar(db,"SELECT COUNT(*) FROM reports WHERE author=? AND created>?",p.getUuid().toString(),System.currentTimeMillis()-600000)>2)throw new IllegalArgumentException("Не более 3 жалоб за 10 минут");Store.update(db,"INSERT INTO reports(author,target,body,location,created) VALUES(?,?,?,?,?)",p.getUuid().toString(),target,body,loc,System.currentTimeMillis());return "Жалоба записана. Спасибо за помощь.";}));return 1;}))));
  d.register(literal("wladmin").requires(s->r.staff(s,"owner")).executes(c->{admin(r,c.getSource());return 1;})
   .then(literal("reports").executes(c->{if(!r.staff(c.getSource(),"owner"))return 0;r.server().getCommandManager().parseAndExecute(c.getSource(),"staff reports");return 1;}))
   .then(literal("resolve").then(argument("id",IntegerArgumentType.integer(1)).then(argument("reason",StringArgumentType.greedyString()).executes(c->{if(!r.staff(c.getSource(),"owner"))return 0;r.server().getCommandManager().parseAndExecute(c.getSource(),"staff resolve "+IntegerArgumentType.getInteger(c,"id")+" "+str(c,"reason"));return 1;}))))
   .then(literal("diag").executes(c->{c.getSource().sendFeedback(()->Text.literal("WarLand ready="+r.ready()+", average tick="+r.server().getAverageTickTime()+"ms, modules="+r.modules),false);return 1;})));
 });}
 public static void main(CoreRuntime r,ServerPlayerEntity p){if(!r.gate(p))return;r.menu(p,"Главное меню",List.of(
  new MenuEntry(Menus.icon(Items.GOLD_INGOT,"Кошелёк","Баланс и начало игры"),()->r.later(p,r.balance(p.getUuid()).thenApply(v->"На счету "+v+" кредитов"))),
  new MenuEntry(Menus.icon(Items.WHITE_BANNER,"Государство","Территории, ранги и дипломатия"),()->nation(r,p)),
  new MenuEntry(Menus.icon(Items.BRICKS,"Город","Строительство и развитие"),()->command(r,p,"city")),
  new MenuEntry(Menus.icon(Items.EMERALD,"Скупщик","Динамические цены и дневные лимиты"),()->command(r,p,"shop")),
  new MenuEntry(Menus.icon(Items.CHEST,"Аукцион","Лоты, покупки, возвраты"),()->command(r,p,"ah")),
  new MenuEntry(Menus.icon(Items.BOOK,"Квесты","Ежедневные задания"),()->command(r,p,"quests")),
  new MenuEntry(Menus.icon(Items.IRON_SWORD,"Война","Мобилизация и расписание"),()->war(r,p)),
  new MenuEntry(Menus.icon(Items.MINECART,"Техника","Магазин и гараж"),()->command(r,p,"vehicle")),
  new MenuEntry(Menus.icon(Items.CLOCK,"События","Недельный календарь"),()->command(r,p,"events")),
  new MenuEntry(Menus.icon(Items.PAPER,"Сезон","Календарь, фазы и история без автоматического вайпа"),()->command(r,p,"season")),
  new MenuEntry(Menus.icon(Items.COMPASS,"Транспорт","Хаб и столица"),()->command(r,p,"warp")),
  new MenuEntry(Menus.icon(Items.WRITABLE_BOOK,"Обучение","Правила и первые шаги"),()->tutorial(r,p,0))));}
 private static void command(CoreRuntime r,ServerPlayerEntity p,String cmd){var dispatcher=r.server().getCommandManager().getDispatcher();if(dispatcher.getRoot().getChild(cmd.split(" ")[0])==null){r.reply(p,"Этот модуль пока не включён в сборку.");return;}r.server().getCommandManager().parseAndExecute(p.getCommandSource(),cmd);}
 private static void nation(CoreRuntime r,ServerPlayerEntity p){var n=r.nations.nation(p.getUuid());if(n==null){r.reply(p,"Создание: /nation create <название>. Вступление: /nation join <название>.");return;}
  r.menu(p,n.name(),List.of(new MenuEntry(Menus.icon(Items.MAP,"Территории","Чанков: "+r.nations.snapshot().claims().values().stream().filter(n.id()::equals).count(),"Новый чанк: /claim"),()->command(r,p,"claim info")),new MenuEntry(Menus.icon(Items.GOLD_INGOT,"Казна","/nation deposit <сумма>","/nation withdraw <сумма>"),()->r.later(p,r.store.submit(c->"В казне "+Store.scalar(c,"SELECT balance FROM accounts WHERE owner=?",Store.nation(n.id()))+" кредитов"))),new MenuEntry(Menus.icon(Items.PAPER,"Налоги","Текущий налог: "+n.tax()+"%","Изменение: /nation tax <0–15>"),()->r.reply(p,"Новый налог вступает в силу через 24 часа.")),new MenuEntry(Menus.icon(Items.WHITE_BANNER,"Участники и ранги","/nation invite <игрок>","/nation rank <игрок> <ранг>","/nation rankcreate <ранг> <права>"),()->r.reply(p,"Права: build,claim,invite,treasury,war,buildings,diplomacy")),new MenuEntry(Menus.icon(Items.WRITABLE_BOOK,"Дипломатия","/nation pact <государство>","Подтверждение обеими сторонами"),()->r.reply(p,"Пакт запрещает взаимное объявление войны на 7 дней."))));}
 private static void war(CoreRuntime r,ServerPlayerEntity p){List<MenuEntry> entries=new ArrayList<>();for(var w:r.wars.wars()){String a=Optional.ofNullable(r.nations.snapshot().nations().get(w.attacker())).map(v->v.name()).orElse("?"),b=Optional.ofNullable(r.nations.snapshot().nations().get(w.defender())).map(v->v.name()).orElse("?");entries.add(new MenuEntry(Menus.icon(Items.IRON_SWORD,a+" ↔ "+b,"Счёт "+w.attackScore()+":"+w.defendScore(),"Подготовка до "+Instant.ofEpochMilli(w.starts()).atZone(Rules.ZONE),"Статус: "+phaseLabel(r.wars.phase(w,System.currentTimeMillis()))),()->r.reply(p,"Окно войны: "+r.wars.windowLabel(w)+" • /war peace <государство> • /war surrender <государство>")));}if(entries.isEmpty())entries.add(new MenuEntry(Menus.icon(Items.WHITE_BANNER,"Сейчас мир","Объявление: /war declare <государство>",r.config.enableWarCapture?"12 часов на подготовку":"Войны закрыты до боевого тестирования"),()->r.reply(p,"Война оплачивается из казны и требует подтверждения.")));r.menu(p,"Войны",entries);}
 private static String phaseLabel(String value){return switch(value){case "MOBILIZATION"->"Мобилизация";case "ACTIVE"->"Боевое окно";case "TRUCE"->"Вне боевого окна";case "ENDING"->"Подведение итогов";case "PEACE"->"Мирный договор";case "DRAW"->"Ничья";case "ATTACKER_WIN"->"Победа атакующих";case "DEFENDER_WIN"->"Победа защитников";default->value;};}
 private static final String[][] TUTORIAL={{"Добро пожаловать","WarLand — политика, экономика и строительство.","На спавне нельзя наносить урон и ломать блоки."},{"Первые деньги","/shop — продажа ванильных ресурсов.","/ah — торговля с другими игроками."},{"Государства","/nation create <название> — собственная страна.","/claim — расширение; /city — здания."},{"Война и риск","После объявления войны есть 12 часов подготовки.","При смерти всё обычное снаряжение выпадает."},{"Честная игра","Запрещены читы, дюпы и обход правил твинками.","/report <игрок> <описание> — жалоба."}};
 private static void tutorial(CoreRuntime r,ServerPlayerEntity p,int step){if(step>=TUTORIAL.length){r.later(p,r.store.tx(c->{Store.update(c,"UPDATE profiles SET tutorial=1 WHERE uuid=?",p.getUuid().toString());return "Обучение завершено. Теперь можно основать государство.";}));return;}String[] page=TUTORIAL[step];r.menu(p,"Обучение "+(step+1)+"/"+TUTORIAL.length,List.of(new MenuEntry(Menus.icon(Items.BOOK,page[0],page[1],page[2]),()->tutorial(r,p,step)),new MenuEntry(Menus.icon(Items.LIME_DYE,step==TUTORIAL.length-1?"Завершить":"Далее"),()->tutorial(r,p,step+1))));}
 private static void admin(CoreRuntime r,ServerCommandSource s){if(s.getEntity() instanceof ServerPlayerEntity p)r.menu(p,"Администрирование",List.of(new MenuEntry(Menus.icon(Items.PAPER,"Жалобы","/wladmin reports"),()->command(r,p,"wladmin reports")),new MenuEntry(Menus.icon(Items.COMPARATOR,"Диагностика","Без доступа к секретам конфигурации"),()->command(r,p,"wladmin diag"))));else s.sendFeedback(()->Text.literal("/wladmin reports | resolve <id> <причина> | diag"),false);}
}
