package ru.warland.content;

import org.junit.jupiter.api.Test;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class ContentRulesTest {
    private static final Instant SATURDAY=Instant.parse("2026-09-05T15:00:00Z");
    private ContentData.Job job(String stage) {
        var j=new ContentData.Job();j.id=UUID.randomUUID().toString();j.owner=UUID.randomUUID().toString();
        j.world="minecraft:overworld";j.plan="depot_v1";j.hash="test";j.price=600;j.y=70;j.stage=stage;
        j.paid=!Set.of("CHARGING","PAYMENT_REVIEW").contains(stage);j.materialsHeld=Set.of("PLACING","BATCH","DONE").contains(stage);return j;
    }
    private ContentData.Profile complete() {var p=new ContentData.Profile();ActivityRules.roll(p,SATURDAY);p.zones.addAll(List.of("market","quests","transport","training"));p.walked=600;p.survey.addAll(List.of(1L,2L,3L,4L,5L,6L));return p;}
    @Test void capitalIsDeterministicAndCompact() {var a=Layouts.capital();var b=Layouts.capital();assertEquals(a.fingerprint(),b.fingerprint());assertEquals(193,a.width());assertEquals(193,a.depth());assertTrue(a.height()<32);assertTrue(a.cells().size()<150_000);}
    @Test void originalPlansNeverContainAirOrFluids() {var plans=new ArrayList<>(Layouts.buildings().values());plans.add(Layouts.capital());for(var p:plans)for(var c:p.cells())assertFalse(Set.of("minecraft:air","minecraft:water","minecraft:lava","minecraft:cave_air","minecraft:structure_void").contains(c.block()));}
    @Test void planCoordinatesAreUniqueAndSorted() {for(var p:Layouts.buildings().values()){Set<BlockPlan.Point> seen=new HashSet<>();int lastY=Integer.MIN_VALUE;for(var c:p.cells()){assertTrue(seen.add(new BlockPlan.Point(c.x(),c.y(),c.z())));assertTrue(c.y()>=lastY);lastY=c.y();}}}
    @Test void allPhysicalBuildingBlocksAreChargedAsMaterials() {for(var p:Layouts.buildings().values())assertEquals(p.cells().size(),p.materials().values().stream().mapToInt(Integer::intValue).sum());}
    @Test void noEconomyCreatingOrHighTickBlocksInPlans() {var list=new ArrayList<>(Layouts.buildings().values());list.add(Layouts.capital());for(var p:list)for(var c:p.cells())assertFalse(c.block().matches(".*(spawner|command_block|structure_block|jigsaw|hopper|redstone|portal|beacon).*"));}
    @Test void cityPlanHasOpenTwoWideEntrance() {for(var p:Layouts.buildings().values())for(int y=1;y<=3;y++)for(int x=p.width()/2;x<=p.width()/2+1;x++){int xx=x,yy=y;assertTrue(p.cells().stream().noneMatch(c->c.x()==xx&&c.y()==yy&&c.z()==0));}}
    @Test void volumeIterationIsComplete() {var p=Layouts.buildings().get("depot_v1");Set<BlockPlan.Point> points=new HashSet<>();for(int i=0;i<p.volume();i++)assertTrue(points.add(p.volumePoint(i)));assertEquals(p.width()*p.depth()*p.height(),points.size());assertThrows(IndexOutOfBoundsException.class,()->p.volumePoint(p.volume()));}
    @Test void baseAndHeadroomExistAtArrivalAndAllWarpDestinations() {var p=Layouts.capital();Set<BlockPlan.Point> solid=new HashSet<>();for(var c:p.cells())solid.add(new BlockPlan.Point(c.x(),c.y(),c.z()));var feet=new ArrayList<BlockPlan.Point>();feet.add(new BlockPlan.Point(0,1,12));for(var z:Layouts.ZONES)feet.add(new BlockPlan.Point(z.x(),1,z.z()+4));for(var f:feet){assertTrue(solid.contains(new BlockPlan.Point(f.x(),0,f.z())));assertFalse(solid.contains(f));assertFalse(solid.contains(new BlockPlan.Point(f.x(),2,f.z())));}}
    @Test void allServiceArrivalsAreReachableOnFoot() {
        var p=Layouts.capital();Set<BlockPlan.Point> solid=new HashSet<>();for(var c:p.cells())solid.add(new BlockPlan.Point(c.x(),c.y(),c.z()));
        Set<BlockPlan.Point> visited=new HashSet<>();ArrayDeque<BlockPlan.Point> queue=new ArrayDeque<>();var start=new BlockPlan.Point(0,1,12);visited.add(start);queue.add(start);
        while(!queue.isEmpty()){var at=queue.remove();for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){var next=new BlockPlan.Point(at.x()+d[0],1,at.z()+d[1]);if(!visited.contains(next)&&solid.contains(new BlockPlan.Point(next.x(),0,next.z()))&&!solid.contains(next)&&!solid.contains(new BlockPlan.Point(next.x(),2,next.z()))){visited.add(next);queue.add(next);}}}
        for(var z:Layouts.ZONES)assertTrue(visited.contains(new BlockPlan.Point(z.x(),1,z.z()+4)),z.name());
    }
    @Test void foliageIsPersistent() {for(var c:Layouts.capital().cells())if(c.block().contains("leaves"))assertTrue(c.block().contains("persistent=true"));}
    @Test void malformedAndEmptyPlansAreRejected() {assertThrows(IllegalArgumentException.class,()->new BlockPlan.Builder("bad").build());assertThrows(IllegalArgumentException.class,()->new BlockPlan.Builder("bad").block(0,0,0,";setblock"));assertThrows(IllegalArgumentException.class,()->new BlockPlan.Builder("bad").box(2,0,0,0,0,0,"minecraft:stone"));}
    @Test void blueprintCollectionsAreImmutable() {var p=Layouts.buildings().get("depot_v1");assertThrows(UnsupportedOperationException.class,()->p.cells().clear());assertThrows(UnsupportedOperationException.class,()->p.materials().clear());}
    @Test void omitDoesNotScheduleDestruction() {var p=new BlockPlan.Builder("test").box(0,0,0,2,0,0,"minecraft:stone").omit(1,0,0,1,0,0).build();assertEquals(2,p.cells().size());assertTrue(p.cells().stream().allMatch(c->c.block().equals("minecraft:stone")));}
    @Test void airIsOnlyPlaceableTarget() {assertEquals(PlacementRules.CellAction.PLACE,PlacementRules.cell(true,true,true,false,false,false));assertEquals(PlacementRules.CellAction.STOP,PlacementRules.cell(true,true,false,false,false,true));}
    @Test void matchingPreexistingBlockNeedsJournalAndIsNeverReplaced() {assertEquals(PlacementRules.CellAction.STOP,PlacementRules.cell(true,true,false,false,true,false));assertEquals(PlacementRules.CellAction.KEEP,PlacementRules.cell(true,true,false,false,true,true));}
    @Test void permissionAndFluidChecksPrecedeIdempotence() {assertEquals(PlacementRules.CellAction.STOP,PlacementRules.cell(false,true,false,false,true,true));assertEquals(PlacementRules.CellAction.STOP,PlacementRules.cell(true,true,true,true,false,true));assertEquals(PlacementRules.CellAction.STOP,PlacementRules.cell(true,false,true,false,false,true));}
    @Test void boundsHandleNegativeCoordinatesAndInclusiveCollision() {var a=new PlacementRules.Bounds(-20,60,-20,-10,65,-10);assertTrue(a.contains(-10,65,-10));assertFalse(a.contains(-9,65,-10));assertTrue(a.intersects(new PlacementRules.Bounds(-10,65,-10,0,70,0)));assertFalse(a.intersects(new PlacementRules.Bounds(-9,65,-9,0,70,0)));}
    @Test void purchasesDefaultOffAndLimitsValidated() {var c=new ContentData.Config();assertFalse(c.buildingPurchasesEnabled);c.validate();c.placementBudget=257;assertThrows(IllegalArgumentException.class,c::validate);}
    @Test void zeroPricesAndUnsupportedConfigRejected() {var c=new ContentData.Config();c.depotCost=0;assertThrows(IllegalArgumentException.class,c::validate);c=new ContentData.Config();c.version=2;assertThrows(IllegalArgumentException.class,c::validate);}
    @Test void corruptedStateFailsClosed() {var d=new ContentData();d.schema=2;assertThrows(IllegalArgumentException.class,d::validate);}
    @Test void unfundedJobCannotPlace() {var d=new ContentData();var j=job("PLACING");j.paid=false;d.jobs.put(j.id,j);assertThrows(IllegalArgumentException.class,d::validate);}
    @Test void interruptedPaymentHasDistinctRecoveryState() {var d=new ContentData();var j=job("CHARGING");d.jobs.put(j.id,j);String id=j.operationId();d.quarantineInterruptedJobs();assertEquals("PAYMENT_REVIEW",j.stage);assertEquals(id,j.operationId());assertFalse(j.paid);}
    @Test void interruptedMaterialIntentNeverAssumesEscrow() {var d=new ContentData();var j=job("MATERIAL_INTENT");d.jobs.put(j.id,j);d.quarantineInterruptedJobs();assertEquals("MATERIAL_REVIEW",j.stage);assertFalse(j.materialsHeld);}
    @Test void interruptedBatchesDoNotAutomaticallyReplay() {for(String stage:List.of("BATCH","PLACING")){var d=new ContentData();var j=job(stage);j.cursor=7;j.batchEnd=12;d.jobs.put(j.id,j);d.quarantineInterruptedJobs();assertEquals("RECOVERY",j.stage);assertEquals(7,j.cursor);assertEquals(12,j.batchEnd);assertTrue(PlacementRules.isProtected(j));}}
    @Test void completedAndAbandonedJobsNeverResume() {for(String stage:List.of("DONE","ABANDONED")){var d=new ContentData();var j=job(stage);d.jobs.put(j.id,j);d.quarantineInterruptedJobs();assertEquals(stage,j.stage);assertFalse(PlacementRules.isProtected(j));}}
    @Test void waitingForMaterialsSurvivesWithoutAnotherPayment() {var d=new ContentData();var j=job("WAITING_MATERIALS");d.jobs.put(j.id,j);d.quarantineInterruptedJobs();assertEquals("WAITING_MATERIALS",j.stage);assertTrue(j.paid);assertFalse(j.materialsHeld);}
    @Test void capCountsCompletedBuildingsButNotAbandonedReservations() {var d=new ContentData();String owner=UUID.randomUUID().toString();for(int i=0;i<3;i++){var j=job("DONE");j.owner=owner;d.jobs.put(j.id,j);}assertTrue(PlacementRules.ownerCapReached(d,owner));d.jobs.values().iterator().next().stage="ABANDONED";assertFalse(PlacementRules.ownerCapReached(d,owner));}
    @Test void recoveryRequiresMeaningfulReason() {assertFalse(PlacementRules.validReason("ok"));assertFalse(PlacementRules.validReason("long\nreason"));assertTrue(PlacementRules.validReason("Инвентарь и блоки сверены по журналу"));assertFalse(PlacementRules.validReason("x".repeat(161)));}
    @Test void repeatedDailyClaimIsIdempotent() {var p=complete();assertEquals(ActivityRules.Claim.GRANTED,ActivityRules.claim(p,"tour",120));for(int i=0;i<100;i++)assertEquals(ActivityRules.Claim.ALREADY,ActivityRules.claim(p,"tour",120));assertEquals(12,p.reputation);}
    @Test void incompleteAndUnknownQuestsCannotReward() {var p=new ContentData.Profile();assertEquals(ActivityRules.Claim.INCOMPLETE,ActivityRules.claim(p,"tour",120));assertEquals(ActivityRules.Claim.INCOMPLETE,ActivityRules.claim(p,"admin",120));assertEquals(0,p.reputation);}
    @Test void weeklyCapDoesNotPartiallyConsumeReward() {var p=complete();p.weekReputation=115;assertEquals(ActivityRules.Claim.WEEKLY_CAP,ActivityRules.claim(p,"tour",120));assertFalse(p.claimed.contains("tour"));assertEquals(0,p.reputation);}
    @Test void exactWeeklyCapIsAccepted() {var p=complete();p.weekReputation=108;assertEquals(ActivityRules.Claim.GRANTED,ActivityRules.claim(p,"tour",120));assertEquals(120,p.weekReputation);}
    @Test void newDayResetsProgressButNotReputation() {var p=complete();ActivityRules.claim(p,"walk",120);ActivityRules.roll(p,SATURDAY.plusSeconds(86400));assertEquals(16,p.reputation);assertTrue(p.claimed.isEmpty());assertEquals(0,p.walked);assertTrue(p.zones.isEmpty());}
    @Test void backwardsClockCannotResetClaimMarkers() {var p=complete();ActivityRules.claim(p,"tour",120);long day=p.day;ActivityRules.roll(p,SATURDAY.minusSeconds(86400*3));assertEquals(day,p.day);assertTrue(p.claimed.contains("tour"));assertEquals(12,p.reputation);}
    @Test void resetUsesMoscowMidnight() {assertEquals(ActivityRules.day(Instant.parse("2026-09-05T20:59:59Z"))+1,ActivityRules.day(Instant.parse("2026-09-05T21:00:00Z")));}
    @Test void mondayResetsOnlyWeeklyBudgetAndEvent() {var p=complete();p.weekReputation=100;p.reputation=500;p.eventStarted=1;p.eventClaimed=true;ActivityRules.roll(p,Instant.parse("2026-09-06T21:00:00Z"));assertEquals(0,p.weekReputation);assertEquals(500,p.reputation);assertFalse(p.eventClaimed);assertEquals(0,p.eventStarted);}
    @Test void weeklyWindowHasExactExclusiveEnd() {var window=ActivityRules.nextOrCurrentEvent(SATURDAY);assertTrue(window.active(SATURDAY));assertTrue(window.active(SATURDAY.plusSeconds(3599)));assertFalse(window.active(SATURDAY.plusSeconds(3600)));assertEquals(SATURDAY.plusSeconds(7*86400),ActivityRules.nextOrCurrentEvent(SATURDAY.plusSeconds(3600)).start());}
    @Test void eventCannotRewardIncompleteOrAfkRun() {var p=complete();p.eventStarted=SATURDAY.toEpochMilli();p.checkpoint=8;assertEquals(ActivityRules.Claim.INCOMPLETE,ActivityRules.claimEvent(p,SATURDAY.plusSeconds(200),120));p.eventWalked=200;assertEquals(ActivityRules.Claim.INCOMPLETE,ActivityRules.claimEvent(p,SATURDAY.plusSeconds(89),120));}
    @Test void eventRewardIsOnePerWeekAndWithinSharedCap() {var p=complete();p.eventStarted=SATURDAY.toEpochMilli();p.eventWalked=200;p.checkpoint=8;assertEquals(ActivityRules.Claim.GRANTED,ActivityRules.claimEvent(p,SATURDAY.plusSeconds(90),120));assertEquals(ActivityRules.Claim.ALREADY,ActivityRules.claimEvent(p,SATURDAY.plusSeconds(91),120));assertEquals(25,p.reputation);}
    @Test void lateEventClaimCannotMintReward() {var p=complete();p.eventStarted=SATURDAY.toEpochMilli();p.eventWalked=300;p.checkpoint=8;assertEquals(ActivityRules.Claim.INCOMPLETE,ActivityRules.claimEvent(p,SATURDAY.plusSeconds(3600),120));}
    @Test void noMovementRewardsForTeleportFlightMountOrCreative() {assertEquals(0,ActivityRules.acceptedMovement(100,true,false,false,false));assertEquals(0,ActivityRules.acceptedMovement(5,false,false,false,false));assertEquals(0,ActivityRules.acceptedMovement(5,true,true,false,false));assertEquals(0,ActivityRules.acceptedMovement(5,true,false,true,false));assertEquals(0,ActivityRules.acceptedMovement(5,true,false,false,true));assertEquals(0,ActivityRules.acceptedMovement(Double.NaN,true,false,false,false));assertEquals(5,ActivityRules.acceptedMovement(5,true,false,false,false));}
    @Test void rankThresholdsAreDeterministic() {assertEquals("Гость столицы",ActivityRules.rank(79));assertEquals("Горожанин",ActivityRules.rank(80));assertEquals("Мастер",ActivityRules.rank(200));assertEquals("Старожил",ActivityRules.rank(500));}
}
